language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install ."
before_script:
  - "python -m nala.download_corpora"
  - "wget http://github.com/downloads/chokkan/crfsuite/crfsuite-0.12-x86_64.tar.gz -O /tmp/crfsuite.tar.gz --no-check-certificate"
  - "tar -xvf /tmp/crfsuite.tar.gz"
script:
  - "nosetests"
  - "python demo_predict.py -c /tmp/crfsuite -d example.txt"
