language: python

python:
  - "3.5"

branches:
  only:
    - master
    - develop

cache:
  pip: true

before_install:
  - pip install codecov

install:
  - pip install .
  - python -m nalaf.download_corpora

script:
  - nosetests -a \"!slow\" --with-coverage
# - python example_annotate.py -p 2581245

after_success:
  - codecov
